import React from "react";
import Head from "next/head";
import Header from "../Header";
import Containers from "./Cards";
import Footer from "../Footer";


export default function SobreComponents() {
    return (
        <>
            <Head>
                <title>fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Containers />
            <Footer />
        </>
    );
}
