import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import {
    Main,
    BannerReceitas,
    ContainerSection,
    Section,
    ContainerIngredients,
    ContainerBake,
    TituloReceitas,
    BoxMinutos,
    ContainerClock,
} from "../components/componentes";
// Styled-Components não estiliza o OBJ [id].js !

function Receita({ exercicio }) {
    console.log(exercicio);
    return (
        <>
            <Head>
                <title>Receitas |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Main>
                <BannerReceitas>
                    <img src={exercicio.img} alt="recipe image" />
                </BannerReceitas>
                <ContainerIngredients>
                    <TituloReceitas>{exercicio.nome}</TituloReceitas>
                    <p>{exercicio.info}</p>
                </ContainerIngredients>
            </Main>
            <ContainerClock>
                <BoxMinutos>
                    <img src="/clock-regular.svg" alt="clock image" />
                    <p>{exercicio.nivel}</p>
                </BoxMinutos>
            </ContainerClock>
            <ContainerSection>
                <Section>
                    <h2>MODO DE PREPARO</h2>
                    <p>{exercicio.modo}</p>
                    <ContainerBake>
                        <img src="/bake.png" alt="bake image" />
                    </ContainerBake>
                </Section>
            </ContainerSection>
        </>
    );
}

export async function getStaticProps({ params }) {
    const exercicio = await fetch(`http://localhost:3001/exe/${params.id}`)
        .then((data) => {
            if (data.ok) {
                return data.json();
            }
            throw new Error("Deu problema");
        })
        .then((dataObj) => dataObj);

    return {
        props: {
            exercicio,
        },
    };
}

export async function getStaticPaths() {
    const exercicios = await fetch(`http://localhost:3001/exe`)
        .then((re) => {
            if (re.ok) {
                return re.json();
            }
            throw new Error(" Problema ao buscar a API ! ");
        })
        .then((reObj) => reObj);
    return {
        paths: exercicios.map((exercicio) => ({
            params: {
                id: exercicio.id.toString(),
            },
        })),
        fallback: false,
    };
}

export default Receita;
