import * as React from "react";
import Header from "./components/Header";
import { Title, Container } from "./components/componentes";
import Cards from "./components/cardModel/card";
import Head from "next/head";

const Receitas: React.FC = () => {
    return (
        <>
            <Head>
                <title>Cards |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <Header />
            <Container>
                <Title>Veja nossas receitas</Title>
            </Container>
            <Cards />
        </>
    );
};

export default Receitas;
