import * as React from "react";
import Header from "./components/Header";
import Cards from "./components/cardModel/card";
import Head from "next/head";
import Filter from "./components/receitas assets/filter";

const Receitas: React.FC = () => {
    return (
        <>
            <Head>
                <title>Cards |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Filter />
            <Cards />
        </>
    );
};

export default Receitas;
