import React from "react";
import Exe from "./components/PageExer";
import Head from "next/head";
import Header from "./components/Header";

export default function Exercicios() {
    return (
        <>
            <Head>
                <title>exercícios |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Exe />
        </>
    );
}
