import React, { useState } from "react";
import Header from "./components/Header";
import IMCFunc from "./components/imc/imc";
import Head from "next/head";

const IMC: React.FC = () => {
    return (
        <>
            <Head>
                <title>IMC |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <IMCFunc />
        </>
    );
};

export default IMC;
