import * as React from "react";
import Header from "./components/Header";
import Cards from "./components/cardModel/card";
import Head from "next/head";
import Filter from "./components/filter/filter";

const Receitas: React.FC = () => {
    return (
        <div className="dark:bg-[#1f1f1f]">
            <Head>
                <title>Cards |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Filter />
            <Cards />
        </div>
    );
};

export default Receitas;
