export const data = [
    {
        id: 1,
        url:"https://i.ibb.co/LNsgSnG/2.png",
        alt:"recipe"
    },
    {
        id:2,
        url:"https://i.ibb.co/crqpgDq/1.png",
        alt:"exercise"
    },
    {
        id:3,
        url:"https://i.ibb.co/GnWhxX6/3.png",
        alt:"imc"
    },
    {
        id:3,
        url:"https://i.ibb.co/GnWhxX6/3.png",
        alt:"imc"
    },
    {
        id:3,
        url:"https://i.ibb.co/GnWhxX6/3.png",
        alt:"imc"
    },
    {
        id:3,
        url:"https://i.ibb.co/GnWhxX6/3.png",
        alt:"imc"
    },
    {
        id:3,
        url:"https://i.ibb.co/GnWhxX6/3.png",
        alt:"imc"
    }
]
