import React, { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import {
    Main,
    BannerReceitas,
    ContainerSection,
    Section,
    ContainerIngredients,
    TituloReceitas,
    BoxMinutos,
    ContainerClock,
} from "../components/componentes";

function Receita({ receita }) {
    console.log(receita);
    const [color,setColor] = useState(receita.color);
    return (
        <>
            <Head>
                <title>{receita.nome}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <div className={`flex items-center justify-center flex-col`} style={{background:`linear-gradient(${color}, #000000)`}}>
                <div className="w-full 380-screen:w-[95%] min-h-[22rem] 380-screen:m-2 p-4 rounded-md bg-[#f8ffe5] bg-opacity-20 backdrop-blur-lg drop-shadow-lg ">
                    <div className="flex items-center justify-center mb-2">
                        <h2 className="font-sans text-[1.4rem] text-[#f8ffe5]">{receita.nome}</h2>
                    </div>
                    <div className="grid justify-center grid-707:justify-around items-center gap-8 grid-cols-[repeat(auto-fit,minmax(300px,0fr))] grid-707:grid-cols-[repeat(auto-fit,minmax(300px,1fr))] p-1 w-full h-full">
                        <div className="relative flex items-center justify-center grid-707:justify-left w-[100%] h-80 grid-707:w-[50%]">
                            <img
                                className=" grid-707:max-w-full grid-707:max-h-full absolute rounded-md shadow-xl"
                                src={receita.img}
                                alt="recipe image"
                            />
                        </div>
                        <div className="w-full flex items-center justify-center">
                            <p className="text-[#f8ffe5] text-lg -m-4 mb-2 w-full">{receita.n}</p>
                        </div>
                    </div>
                </div>
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                {/* <div>
                    <BoxMinutos>
                        <img src="/clock-regular.svg" alt="clock image" />
                        <p>{receita.m}</p>
                    </BoxMinutos>
                </div>
                <ContainerSection>
                    <Section>
                        <h2>MODO DE PREPARO</h2>
                        <p>{receita.p}</p>
                    </Section>
                </ContainerSection> */}
                
            </div>

            <Footer />
        </>
    );
}

export async function getStaticProps({ params }) {
    const receita = await fetch(
        `https://api-fake-fitness-express.herokuapp.com/cards/${params.id}`
    )
        .then((data) => {
            if (data.ok) {
                return data.json();
            }
            throw new Error("Deu problema");
        })
        .then((dataObj) => dataObj);

    return {
        props: {
            receita,
        },
    };
}

export async function getStaticPaths() {
    const receitas = await fetch(
        `https://api-fake-fitness-express.herokuapp.com/cards`
    )
        .then((re) => {
            if (re.ok) {
                return re.json();
            }
            throw new Error(" Problema ao buscar a API ! ");
        })
        .then((reObj) => reObj);
    return {
        paths: receitas.map((receita) => ({
            params: {
                id: receita.id.toString(),
            },
        })),
        fallback: false,
    };
}

export default Receita;
