import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import {
    Main,
    BannerReceitas,
    ContainerSection,
    Section,
    ContainerIngredients,
    ContainerBake,
    TituloReceitas,
    BoxMinutos,
    ContainerClock,
} from "../components/componentes";
// Styled-Components não estiliza o OBJ [id].js !

function Receita({ receita }) {
    console.log(receita);
    return (
        <>
            <Head>
                <title>Receitas |fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Main>
                <BannerReceitas>
                    <img src={receita.img} alt="recipe image" />
                </BannerReceitas>
                <ContainerIngredients>
                    <TituloReceitas>{receita.nome}</TituloReceitas>
                    <p>{receita.n}</p>
                </ContainerIngredients>
            </Main>
            <ContainerClock>
                <BoxMinutos>
                    <img src="/clock-regular.svg" alt="clock image" />
                    <p>{receita.m}</p>
                </BoxMinutos>
            </ContainerClock>
            <ContainerSection>
                <Section>
                    <h2>MODO DE PREPARO</h2>
                    <p>{receita.p}</p>
                    <ContainerBake>
                        <img src="/bake.png" alt="bake image" />
                    </ContainerBake>
                </Section>
            </ContainerSection>
        </>
    );
}

export async function getStaticProps({ params }) {
    const receita = await fetch(`http://localhost:3001/cards/${params.id}`)
        .then((data) => {
            if (data.ok) {
                return data.json();
            }
            throw new Error("Deu problema");
        })
        .then((dataObj) => dataObj);

    return {
        props: {
            receita,
        },
    };
}

export async function getStaticPaths() {
    const receitas = await fetch(`http://localhost:3001/cards`)
        .then((re) => {
            if (re.ok) {
                return re.json();
            }
            throw new Error(" Problema ao buscar a API ! ");
        })
        .then((reObj) => reObj);
    return {
        paths: receitas.map((receita) => ({
            params: {
                id: receita.id.toString(),
            },
        })),
        fallback: false,
    };
}

export default Receita;
