import React from "react";
import Head from "next/head";
import Header from "./Header";
import { Footer } from "./componentes";
import Containers from "./Container-Landing/index";

export default function LandingPage() {
    return (
        <>
            <Head>
                <title>fitnessExpress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Containers />
            <Footer>
                <p>&copy;Dalves-Fitness-express-2021</p>
            </Footer>
        </>
    );
}
